spring:
  application:
    name: auth-service

  # Move these out of the 'application' block
  datasource:
    url: jdbc:postgresql://postgres.railway.internal:5432/Auth
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085
  servlet:
    context-path: /api